server:
  port: 8091


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scott
    username: scott
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: messages/message
    encoding: utf-8

