server:
  port: 8091


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scott
    username: scott
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: messages/message
    encoding: utf-8

mybatis:
  mapper-locations: classpath:mappers/*.xml   # Mapper XML 파일 위치
  type-aliases-package: com.multi.crud_subject.board.model.dto
  configuration:
    map-underscore-to-camel-case: true        # DB 컬럼명 (snake_case) → Java 필드명 (camelCase) 자동 매핑
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # SQL 로그 콘솔 출력